version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: utkarshkarambhe
      POSTGRES_PASSWORD: gmail1234
      POSTGRES_DB: stock_data  # Changed from 'airflow' to match your project
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialize schema

  webserver:
    image: apache/airflow:2.6.3
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://utkarshkarambhe:gmail1234@postgres/stock_data
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: '8080'  # Container port
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/scripts:/opt/airflow/scripts
      - ./airflow/logs:/opt/airflow/logs
    ports:
      - "1234:8080"  # Host:Container
    depends_on:
      - postgres
    command: webserver

  scheduler:
    image: apache/airflow:2.6.3
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://utkarshkarambhe:gmail1234@postgres/stock_data
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/scripts:/opt/airflow/scripts
    depends_on:
      - postgres
    command: scheduler

  dashboard:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    environment:
      DB_CONN: postgresql://utkarshkarambhe:gmail1234@postgres/stock_data
    ports:
      - "8501:8501"
    depends_on:
      - postgres

volumes:
  postgres_data: